"""rename biography to bio

Revision ID: 8f4222f31b82
Revises: 006bb55d9f59
Create Date: 2026-03-08 13:40:02.811363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4222f31b82'
down_revision: Union[str, Sequence[str], None] = '006bb55d9f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('bio', sa.Text(), nullable=True))
    op.drop_column('authors', 'biography')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('biography', sa.TEXT(), nullable=True))
    op.drop_column('authors', 'bio')
    # ### end Alembic commands ###
